# Generated by Django 5.2.4 on 2025-09-24 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('permission_granted', '授予权限'), ('permission_revoked', '撤销权限'), ('group_added', '加入组'), ('group_removed', '移除组'), ('access_denied', '访问被拒绝'), ('access_granted', '访问允许')], max_length=20, verbose_name='操作类型')),
                ('resource', models.CharField(max_length=200, verbose_name='资源')),
                ('permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='组')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('message', models.TextField(blank=True, null=True, verbose_name='消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限日志',
                'verbose_name_plural': '权限日志',
                'db_table': 'permission_permissionlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='电话')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'permission_userprofile',
            },
        ),
    ]
