# Generated by Django 5.2.4 on 2025-09-24 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permission_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('title', models.CharField(max_length=100, verbose_name='菜单标题')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='链接地址')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('submenu', '子菜单'), ('action', '操作')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission_app.menuitem', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'db_table': 'permission_menuitem',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserMenuLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_app.menuitem', verbose_name='菜单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户菜单日志',
                'verbose_name_plural': '用户菜单日志',
                'db_table': 'permission_usermenulog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='用户组')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_app.menuitem', verbose_name='菜单')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '菜单权限',
                'verbose_name_plural': '菜单权限',
                'db_table': 'permission_menupermission',
                'unique_together': {('menu', 'group', 'user')},
            },
        ),
    ]
